# Generated by Django 4.1.7 on 2023-07-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_vagasemprego_pdf_alter_vagasemprego_tipo_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='link_vaga',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link da vaga'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PE', 'Projeto de extensão'), ('ES', 'Estágio'), ('PP', 'Projeto de Pesquisa')], max_length=2),
        ),
    ]
