# Generated by Django 4.1.7 on 2023-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_vagasemprego_link_vaga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PD', 'Projetos de desenvolvimento'), ('ES', 'Estágio'), ('PP', 'Projeto de Pesquisa'), ('PE', 'Projeto de extensão')], max_length=2),
        ),
    ]
