# Generated by Django 4.1.7 on 2023-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_vagasemprego_tipo_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagasemprego',
            name='area',
            field=models.CharField(choices=[('Adm', 'Administração'), ('Eco', 'Ecologia'), ('Dsg', 'Design'), ('Atp', 'Antropologia'), ('CC', 'Ciências Contábeis'), ('Sec', 'Secretariado'), ('Mat', 'Matemática'), ('Ped', 'Pedagogia'), ('Com', 'Computação')], default='Com', max_length=3),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='nome_empresa',
            field=models.CharField(max_length=17, verbose_name='Nome empresa ou nome projeto'),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PE', 'Projeto de extensão'), ('PIC', 'Projeto de iniciação científica'), ('ES', 'Estágio'), ('PD', 'Projetos de desenvolvimento'), ('PIT', 'Projeto de iniciação tecnológica')], max_length=3),
        ),
    ]
