# Generated by Django 4.1.7 on 2023-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_vagasemprego_area_alter_vagasemprego_nome_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='area',
            field=models.CharField(choices=[('Adm', 'Administração'), ('Com', 'Computação'), ('Sec', 'Secretariado'), ('CC', 'Ciências Contábeis'), ('Dsg', 'Design'), ('Eco', 'Ecologia'), ('Ped', 'Pedagogia'), ('Mat', 'Matemática'), ('Atp', 'Antropologia')], default='Com', max_length=3),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('ES', 'Estágio'), ('PIC', 'Projeto de iniciação científica'), ('PIT', 'Projeto de iniciação tecnológica'), ('PE', 'Projeto de extensão'), ('PD', 'Projetos de desenvolvimento')], max_length=3),
        ),
    ]
