# Generated by Django 4.1.7 on 2023-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_vagasemprego_link_empresa_ou_pesquisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagasemprego',
            name='area',
            field=models.CharField(choices=[('Eco', 'Ecologia'), ('Dsg', 'Design'), ('Ped', 'Pedagogia'), ('Com', 'Computação'), ('CC', 'Ciências Contábeis'), ('Mat', 'Matemática'), ('Atp', 'Antropologia'), ('Adm', 'Administração'), ('Sec', 'Secretariado')], default='Com', max_length=3),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('PD', 'Projetos de desenvolvimento'), ('PIT', 'Projeto de iniciação tecnológica'), ('PIC', 'Projeto de iniciação científica'), ('ES', 'Estágio'), ('PE', 'Projeto de extensão')], max_length=3),
        ),
    ]
