# Generated by Django 4.1.7 on 2023-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_vagasemprego_area_alter_vagasemprego_tipo_vaga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagasemprego',
            name='beneficios',
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='area',
            field=models.CharField(choices=[('CC', 'Ciências Contábeis'), ('Eco', 'Ecologia'), ('Sec', 'Secretariado'), ('Dsg', 'Design'), ('Mat', 'Matemática'), ('Adm', 'Administração'), ('Ped', 'Pedagogia'), ('Atp', 'Antropologia'), ('Com', 'Computação')], default='Com', max_length=3),
        ),
        migrations.AlterField(
            model_name='vagasemprego',
            name='tipo_vaga',
            field=models.CharField(choices=[('ES', 'Estágio'), ('PIT', 'Projeto de iniciação tecnológica'), ('PIC', 'Projeto de iniciação científica'), ('PD', 'Projetos de desenvolvimento'), ('PE', 'Projeto de extensão')], max_length=3),
        ),
    ]
